version: '2'
services:
  db:
    container_name: POSTGRES_CM_DB
    image: postgres:11.2-alpine
    environment:
      - TZ=America/Fortaleza
      - POSTGRES_DB=cm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
